Update Debian10

diff --git a/Debian10 b/Debian10
--- a/Debian10
+++ b/Debian10
@@ -1,4 +1,125 @@
 #!/bin/bash
-#VPS Script By   : Dope-Kid
-#Contact Me FB   : https://www.facebook.com/joash.singh.90
-iXfUqkOFMzTPfdkjgTEnvpReDNMoYXzZXnAuJuBAfoQddKbZoVBvORwkXRqCtlZdbeYrYCELWQuigBVfyTfBVPofZVJtOXndqSpc="PKPrsxFJIuXcqzXeiwTsVEVzCjhOrshaNhnMmdGcHTFjbFPMAnaCjhbLCeXEAPwVVzHymmYDQqkOsuqTXWjYZzwJunvlZcouPslw";lBkeWoKFUFFlKShhbCIoWbCiOQYWvYfsjflHsUSUdqoGsxiQMbZJbIpupxaeNjHMujnMFCJRpbJsTvIxgfyMSfMsCkLpRQHwXiFT="HEWratSyhSweCrIwntKteiKJSzCABXzlMEaTYhlLcWLSGeXxHBziHcmnBebyPxdWkBryakxoUukWuKfaqOSSazMOHqDgIBJleXAF";JGCxcIHoLfEOtksdLiWPFMhDStqtnzMCCYzqosxNDEsOOHFRSsSYXCbMHfiDvURISNBZgGptqyzQaaRpRHJzWLHjimHYgYBuxFKv="ch";oKkrACJwHwAoUukjizFHZeMWgFfBGdSuqLsfSDcbAeWceisFhBGWKvjeLbpZfHsineinBQOVWSrKLsOAxGEbgHwusFQiDiqEIgFY="4";huEiIADoiSYWsgEqGXfygriybdNIvwJoqdJmWQGywpIeATgaQWtNnHZRYEGSecApsBYeMdhFGwJsCSIgXjXRYhbNVSHuRbGtmPoX="";ulSNRseNHzaCzHqxTfOUYfYstEpvKQKsSRbJamsDgWUNBhSQXZUikbBYeDdJVrBHxXzbKFhOXMkLNdUEHPBoleAFbTDkXnqotVnZ="rzHHNjYTrjURohLufqyzcXOQcXTlrLFOTvlnEkyqgSFAfdjBuqCpKmXNiSmyLORgrXviLTVePsNcLfQZtbLaodTxpBJEGZDLlIkZ";LBgguvgxaXSwvGsnqmKWqsJHgsfwcoHduKikrwZiWTydIhTpInPcbqWbrZTvYRsZfrSdFrCCRgCsjcuqMyXvHWNuxsJrGIsudboK=" KATMuFWaiVGRgYWLg0mcKIiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgISP90TP90TP90TP90TP90TP90TP90TP90TP90TPt0TP90TP90TP90TP90TP90TP90SP90TP90TP90TP90TP90TP90TP90TP90TP90jIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgIiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgISLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0iIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgICM54Can5Waz5CazF2bq9SZt5iYGBiOgACIgACIgACIgACIgACIgs2bvJWZjFmRg0CIgAiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgAiIzEDO1gDO2QDOwAiOgACIgACIgACIgACIgACIgAHchNHdhh2Vg0CIgAiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgAiIodmbpN3XoNXYvp2Ll1mLUBiOgACIgACIgACIgACIgACIg0WYydWZsVGVg0CIgAiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgAiIkl2a+VGcvREIhtWQgg2ch9mSgoDIgACIgACIgACIgACIgACIulWYN9idlREItACIgICIvh2YlpAd4RnLsxWY0Nnbp1yZvxGIh1CIlVGdgwHIgIiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgIyL5gjOQlUWNRyLvoDc0RHagoDIldWYwJWZXBicvRXau9WTg4EUW5WZw9EItACIgICIvh2YlpAd4RnLsxWY0Nnbp1yZvxGIh1CIlVGdgwHIi8CUJlVTk8yL6AHd0hGI6ACbl5WYQBCSTNFImAiTQZ1TgUGbw1WaTBSLgACIiAyboNWZKQHe05CbsFGdz5Watc2bsBSYtASZlRHI8BiIuBndv5CZptWZw9GRvAVSZ1EJv8iOwRHdoBiOgcWam52bDBiTQZlblB3TgQWYvxmb39GRg0CIgAiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgICMwADMxoDUJlVTk8yL6AHd0hGI6ACIgACIgASZnFGUg4Wan9GTg4WatJWZXBSLgACIiAyboNWZKQHe05CbsFGdz5Watc2bsBSYtASZlRHI8BCIi0lRG90WgoDIgACIgACIgACIgACIgACIgACIgYjdQlEItACIgICIvh2YlpAd4RnLsxWY0Nnbp1yZvxGIh1CIlVGdgwHIgISXGZ0TbBiOgACIgACIgACIgACIgQ3bvJWZS1yb0VXQg0CIgAiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgAiId50TbBiOgACIgACIgACIgACIgACIgMXZsJWY0BVSg0CIgAiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgAiId50TbBiOgACIgACIgACIgACIgACIgACIlRXYsZGRg0CIgAiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgAiId50TbBiOgACIgACIgACIgACIgACIg4WYCJDbpFmRg0CIgAiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgAiIpIzKgQVTHhCInJXdiNXZu5WYo9mSvE2YpJnZBBiOgACIgACIgACIgACIgACIgUmbvpXZtlGVg0CIgAiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgAiIzVmc1RXYlZEIyVGa09EImAibvlGdh1mcvZmbJBiclZnclNFI+4jPgACIiAyboNWZKQHe05CbsFGdz5Watc2bsBSYtASZlRHI8BCIiICIvh2YlpAd4RnLsxWY0Nnbp1yZvxGIh1CIlVGdgwHIgICM4gDI6ACIgAyUMRFIl52bOByczVGbWBSWBJlMWBSLgACIiAyboNWZKQHe05CbsFGdz5Watc2bsBSYtASZlRHI8BCIiMDN0UDI6ACIgACIgACIgMFTUByczVGbWBSWBJlMWBSLgACIiAyboNWZKQHe05CbsFGdz5Watc2bsBSYtASZlRHI8BCIiIDOgoDIgACITxEVgUmbv5EIzNXZtZFIZFkUyYFItACIgICIvh2YlpAd4RnLsxWY0Nnbp1yZvxGIh1CIlVGdgwHIgIyM0QDI6ACIgACIgACIgMFTUByczVWbWBSWBJlMWBSLgACIiAyboNWZKQHe05CbsFGdz5Watc2bsBSYtASZlRHI8BCIikDOgwCM4AiOgACIgACIgACIgACIgACIgACIggnbpdmTg0CIgAiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgAiIwAzM3ACLwAjM3ACLwATM3AiOgACIgACIgACIgACIgACIgACIuBndkFmQg0CIgAiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgAiIpIXZ2JXZTBCUJByb0BCdp1WashCIwgDM4ACL4ITMzAiOgACIgACIgACIgACIgkHevJHUgQWa1F3Ug0CIgAiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgAiIzQTMgwSOwEDI6ACIgACIgACIgACIgACIgAichVmYw9mcEBSLgACIiAyboNWZKQHe05CbsFGdz5Watc2bsBSYtASZlRHI8BCIiIDN0AiOgACIgACIgACIgACIgACIgQDbl5mb1R3Ug0CIgAiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgAiI0kTMxACUDRFI6ACIgACIgACIgACIgACIgACIOBlVuVGcPBSLgACIiAyboNWZKQHe05CbsFGdz5Watc2bsBSYtASZlRHI8BCIiIjMgoDIgACIgACIgACIgACIgACIgg0UT5WZw9EItACIgICIvh2YlpAd4RnLsxWY0Nnbp1yZvxGIh1CIlVGdgwHIgICdy9GUgYCIlNWa2JXZTBiP+4DIgAiIg8GajVmC0hHduwGbhR3culWLn9GbgEWLgUWZ0BCfgAiIiAyboNWZKQHe05CbsFGdz5Watc2bsBSYtASZlRHI8BiIt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLt0SLiAyboNWZKQHe05CbsFGdz5Watc2bsBSYtASZlRHI8BiIiAyboNWZKQHe05CbsFGdz5Watc2bsBSYtASZlRHI8BiI90TP90TP90TP90TP90TP90TP90TP90TP90TP90STVlUTFJFUgQFUJJ1QT9EVVFUL90TP90TP90TP90TP90TP90TP90TP90TP90TPiAyboNWZKICIiAyboNWZKISIhQURUVETQ10TDBiTFVkQgMVQIBiTPlEVBxETBR1UOlkIg8GajVmCiAiIg8GajVmCyFWZsNmCyVmdvUWbvh2Lg4DIiEjLxICIvh2YlpgbvlGdh1mcvZmbJBCdwlmcjNFIjogCkNmClxWam9mcw9yY0V2Lg4jPgISRMlkRUNVSIBCdlNnb1JCIvh2YlpwYtASey9GdzlGaKcmbph2cp5WaGByIKoAaz5Cd21ycul2L092by9CIm1CItJnCwVHdlN1L092by9CIm1CItJnCzVGbpZEIu9Wa0FGbsFGdz5WSgUmdv1WZSByIKoAMwUDIzRnbllGbj1Ceh1WLtACMwMzN6EjLw4CMucjMxAickRWYt4WZ0NXas1SLgc3ZwRWdt4Gc2RWYiBibwZHZhJGIT1GZtAiblVmcjNnCwATNgMHduVWasNWL4FWbt0CIwAjM3oTMuAjLw4yNyEDIyRGZh1iblR3cpxWLtAydnBHZ11ibwZHZhJGIuBndkFmYgMVbk1CIuVWZyN2cKADM1Ayc05WZpx2YtgXYt1SLgADMxcjOx4CMuAjL3ITMgIHZkFWLuVGdzlGbt0CI3dGckVXLuBndkFmYg4Gc2RWYiByUtRWLg4WZlJ3YzpAdyFGdzVmcg4WatJWZ39CZuQXaul2LjRXZvoAdyFGdzVmcgQWa1F3cvQmL0lmbp9yY0V2LKQWYvxWZy1ibv1WZhRGIsR3YtVGdzl3cKQnchR3clJHIpd2c3VHIlNWa2JXZzpAdyFGdzVmcgQDbl5mb1R3cvQmL0lmbp9yY0V2LKQnchR3clJHIuFmYywWahZ2Lk5Cdp5WavMGdl9iC0JXY0NXZyBichVmYw9mck9CZuQXaul2LjRXZvoAdyFGdzVmcgg2cz9CZuQXaul2LjRXZvoAdyFGdzVmcg42byN2Lk5Cdp5WavMGdl9iC0JXY0NXZyBibwZnblB3bvQmL0lmbp9yY0V2LKQnchR3cggnbpdmbvQmL0lmbp9yY0V2LKwWb0h2XjlGbiVHcvMHc29SZt9GavASY0FGZtc3d3pTY0FGZtc3d3BiUtAib39GajpwclNWa2JXZTByZulGdyFGdzVmUgMiCKg2c8xGb152L2VGZvAybtASLg8ULgg2cuQHcpJ3Yz1Wdp1WZyBXLsxWY0Nnbp9SduVWTvMXZjJXdvNXZS9ibpFWbvATMuFWaiVGR0BXayN2UvRXdB9CMzQWarVGcvR2Lt92YuQnblRnbvNmclNXdiVHa0l2ZucXYy9yL6MHc0RHagQXZndnCkNmC0BXayN2cgQWYvxmb39GZgMiC0BXayN2UgwGbhR3culEIjogCwVHdlN1LuACc1RXZTByUtAiblVmcjNHImYCIwVHdlNFI4tCIk9WboNGImYCIwVHdlN1LzV2YpZnclN1LzV2YyV3bzVmUv4Wah12LwEjbhlmYlREdwlmcjN1b0VXQvAzMkl2alB3bk9SbvNmL05WZ052bjJXZzVnY1hGdpdmL3Fmcv8iOzBHd0hGI0V2Z3pgTQZ1Tvg0UTBCbsFGdz5WSgMiCK4Wah12bk9Cdv9mcvAiP+AiI0N3boRiIg8GajVmCm52bj5ycwZHcp9CdwlmcjNXLtVXatVmcw9iYpx2LyFmdvAiP+AiI0N3boRSPQlkIg8GajVmC0N3boBiIgojbpFWbvREIvASZtFmb0N3bIJCIw1CIkFWZypgI9NkT7RiUFRlTFBySDlETDBSRTFURMBFIsUETCFETJFkVBBCVP5EIGlEIsUUTB5EVT9ESv4USB10TEJUVTByUQZFIFhEVgIVRU5UR95WZlJ3Z7RiIgUWLg8GajVmC7QHcpJ3Yz1Sb1lWblJHcvIWas9ichZ3LgIXaktWbKM3ZulGd0V2Ug4Wah12bkJWdTByIKoQampQMgQXa4VmCi03QOtHJu4iLEVUSOVERgM1UFN0QB1nblVmcntHJiASZtAyboNWZKU2csVmCi03QOtHJu4iLEVEVOFkUHByUTV0QDFUfuVWZyd2ekICIl1CIvh2YlpgblhGdgsTXg4USalEJg0DIQlUWNRCIbBiZppQKgAVSZ1EJgAXZydGI8BycwZHcp9ycyV2cV9yclNmc192clJ1LulWYt9CMx4WYpJWZERHcpJ3YT9Gd1F0LwMDZptWZw9GZv02bj5CduVGdu92YyV2c1JWdoRXan5ydhJ3LvozcwRHdoBCbyV3YggCJ94USalkCi03QOtHJTNVRDNUQgQFUJJ1QTByROl0SDVESD1nblVmcntHJiASZtAyboNWZKsTKt92YuAXa6FGauF2YpBSLPFXLgQXZndHKk0DUJlVTKAyczV2YjFEI0BXayN2UgMiCKETP2YHcp9VZsJWYzlGZuQHb1FmZlRmLm52bj5iN2BXauQXZuBydtACb0N2c5NHImYCIx0jN2BXafVGbiF2cpRmLsxWYuYmbvNmL2YHcp5Cdl5GI31CIsR3Yzl3cKwmc1NGIzxWa0VXZy92YgAXa6dGIyAXa6JGI51CIsxWY0NnbpBCdwFmCiVncn1SZ0FGZwVnC51CIlRWYydGc1BCdwFmC51CIlRXYkBXdgQHchpAduVWblJXa1FXZSByIKowJtBzWlx1J9MkTKcSbyMzOwsVZcdSPuVWZydmCn0WMzsTMbVGXn0DZlJnCzJXdvx2bDByIKoQampQMgQXa4VmCiQWZ0J3bwBXdzBCdv5GIzlGIaZlblB3TiAyboNWZK4WZoRHI70FIionduVGcvJCI90DIikCdylmdtQ3YlRXZk1CZtVGdzl3coQiIgsFImlmCtVGdzl3Ugs2Ylh2QgMiCKkmZKEDI0lGelpgI092byBychBCdwlmcjNHIzlGa0Bib1JHIvRHIkVWZuBSdvllIg8GajVmCuVGa0ByOdBCMgUmbtAiI9RUSVV0ekICIbBiZppAdv9mUgs2Ylh2QgMiCKATOug2Zul2cug2ch9mav02bj5yav9mYlNWYm5yd3d3LvozcwRHdoBiOgACICZEIl1EI0NWY052bDNiCkl2StUGcvREI6ACIgknQgQHcpJ3YTByUQZ1IKg2chJ2LulmYvEyI | r";hKdovGkHCfOZaeluognlzHkIYmnYQUFgtievhApuvVzwToAtRuPjwEzkmRfqPCqSzDrPsfbtApkOlIBkXiQCNwbAihuCpVOKPLhc="kaodAxmnVyFEHSNbOMTWaSkpNuOrQKPdFvjFFPNYrwQHECvnlKYrflfHryrrcBWEAthVKdVNncPdRcqxWyaUaSZIwkZPjtOemlhO";jcHEHcQglSZvUiatbuvOPoUXhpsHxXAoqRyQgpSWWPzwBPthKZcVpqhhLnWZLgDomjfNlnRmeBGkwHrGFeGsDBXmgRUspsXUpKuE="";kbSnjgFDWSpBMNyUFvClBRjDKcJnflTeHXmTeICiWxRRXdYFjQrfTzZrTXcHQumuLHILgAmIYbUgXLumBFlKovSUpgkQPujKwdoh="as";RZaHBNdBmioAWRrBwrkpTDriDtHIACJfEcMoXuYlfnTMDIxtniyqglVjnJaSMaqKRiqhaFxbbkOayBcFSiCGkKrHxYhCUuYKOfim="YXPtNVhJMlriBKSiCOeVaHofSCWYxxjCkUSBUTTwtZwRQodxPirwtPSQXWYExLDPykmzrACRVjWYeUzvoiIgiPNDvJGSGDtoiggo";yqCtcWQLlnWjDojmhvsfoWZzOJRYyzhCLdlbeCYFWikkyLsRjXzBuWQFRKUzZAJPDTtLlsdNAbXEHPBQcudfRZJGLBfaxuhSrHpg="BClFHsTRYoNrcjfXNddXsralFdrlPJNtsocZndxWRqfHAvdQsTysaRJFuxDfxMFJUsBxiywjlKaTrIDaHGjLicqlhNdNUKdkxKSJ";tlyzdpsiNnrSnPmexkexsWmbIHDWAtMdYDgjclEytTBevfuxlpvnVBSHvMpTgHpPCDsfljuvLULUpVJFFbcyiIOiqoKWorECZHSU="o";aGFmicZgZXavOZFVqEiajqSDPuDJacxULEgCmGLxXSiWlYyZpcRvXMuRkdkgEtwQQIAPopLmmvScLANRayKUMEyDZXxljQIyPgbm="6";sIZaUSQAbPiyCkhuWlWwbZOmZLdAKYMJOtkoXjdOqVLdfrRqNQpGhOCGGHrRiiPHacqKHUJtaGwqrRCTKYfJgxBiEYRIyUIcLJOJ="UxPmRBDrjoltvqHPFYfMcmRoItOScqslsvNfaFKNIcMAziMMLFVJMplEUtAXpXYKjorQgSyxqttlUgrpUIszOQBQbiarIutASMMH";KPWGLNMSJJyHnwXWsuliCnDWpTCqUYdRhcKYKMdaTliMzOUSMWpEAjhYQTpXtHLUCGmeGUkBsbFTykIRahdmVYfekDkkerxpRXIA=" -d";XbrQbsiVnbSSubVplItaVoVqRYrEDtyjPvnjdwKjEJcQWgmJzHAEcbzzingmhmjvdVQqKZvybgVUeGOIMMutvRsSNHUQYFhHDttO="UxMXjXrdLcVpuVYXPqjNlyMqovYTJMniTFIcPGzgHBwlVWseWHoXOuIFhOKRuWpIZaRngRGUFGbRlMxVJRwMIsOHEQxyLIyeDQph";nfUYNSjAcXnBoeOzntmaVhgbsxdINDPpQKyfWVeQDRmLaZphpUTUyiPQxIuRnSNVKLKRXYjaTrftgzMtSmHMAGGXbsyALQswfGtT="";nXNhzeYedfSaIgJRDPaotluOeLfmGZWQuQSaKbvltENAFfROrRdcesOVJTsEVrbKVTJdkdWSjmHwVSfjicXoDJHQqfPnkaQNnytO="b";nxOmqqginHKjYYoytWTHPJNKcLTpfLVQocbLKIxrvYLmLWIuWcDvazZvRyGcipvpInZUPUuiTSQMbZfmguXGsjIEdZDBrgcbJLrr="e";zWETfOnZZvxWrBbfoGiCeORjpIVggfDjRifjWfqfrPbdFznVMwOQnXazIONBWTFXPUjvZRVZzamRHhODoNsyPHmrmCYuPEqJfSnn="v |";Tx=Eds;ZbpOzItuHPZrcAAQPXHLZMNMOqkvszNgKTOItbWwZJGIjHHQZvcPVyZujttfoeFKcQkbkbRfHhgbvTbWNayiPDZkUyBZpBQAUxTs="";VjrppsFvCKyjMwtYElmbJsPwDMWqNrrRbWhYHTyikAooLqLqAkBESezjDFkYKdlatbiGSssqBRVVrvclSSztxJKzEibTdYjqSRmP=$(eval "$jcHEHcQglSZvUiatbuvOPoUXhpsHxXAoqRyQgpSWWPzwBPthKZcVpqhhLnWZLgDomjfNlnRmeBGkwHrGFeGsDBXmgRUspsXUpKuE$nxOmqqginHKjYYoytWTHPJNKcLTpfLVQocbLKIxrvYLmLWIuWcDvazZvRyGcipvpInZUPUuiTSQMbZfmguXGsjIEdZDBrgcbJLrr$JGCxcIHoLfEOtksdLiWPFMhDStqtnzMCCYzqosxNDEsOOHFRSsSYXCbMHfiDvURISNBZgGptqyzQaaRpRHJzWLHjimHYgYBuxFKv$huEiIADoiSYWsgEqGXfygriybdNIvwJoqdJmWQGywpIeATgaQWtNnHZRYEGSecApsBYeMdhFGwJsCSIgXjXRYhbNVSHuRbGtmPoX$tlyzdpsiNnrSnPmexkexsWmbIHDWAtMdYDgjclEytTBevfuxlpvnVBSHvMpTgHpPCDsfljuvLULUpVJFFbcyiIOiqoKWorECZHSU$LBgguvgxaXSwvGsnqmKWqsJHgsfwcoHduKikrwZiWTydIhTpInPcbqWbrZTvYRsZfrSdFrCCRgCsjcuqMyXvHWNuxsJrGIsudboK$nxOmqqginHKjYYoytWTHPJNKcLTpfLVQocbLKIxrvYLmLWIuWcDvazZvRyGcipvpInZUPUuiTSQMbZfmguXGsjIEdZDBrgcbJLrr$zWETfOnZZvxWrBbfoGiCeORjpIVggfDjRifjWfqfrPbdFznVMwOQnXazIONBWTFXPUjvZRVZzamRHhODoNsyPHmrmCYuPEqJfSnn$jcHEHcQglSZvUiatbuvOPoUXhpsHxXAoqRyQgpSWWPzwBPthKZcVpqhhLnWZLgDomjfNlnRmeBGkwHrGFeGsDBXmgRUspsXUpKuE$nXNhzeYedfSaIgJRDPaotluOeLfmGZWQuQSaKbvltENAFfROrRdcesOVJTsEVrbKVTJdkdWSjmHwVSfjicXoDJHQqfPnkaQNnytO$ZbpOzItuHPZrcAAQPXHLZMNMOqkvszNgKTOItbWwZJGIjHHQZvcPVyZujttfoeFKcQkbkbRfHhgbvTbWNayiPDZkUyBZpBQAUxTs$kbSnjgFDWSpBMNyUFvClBRjDKcJnflTeHXmTeICiWxRRXdYFjQrfTzZrTXcHQumuLHILgAmIYbUgXLumBFlKovSUpgkQPujKwdoh$nxOmqqginHKjYYoytWTHPJNKcLTpfLVQocbLKIxrvYLmLWIuWcDvazZvRyGcipvpInZUPUuiTSQMbZfmguXGsjIEdZDBrgcbJLrr$aGFmicZgZXavOZFVqEiajqSDPuDJacxULEgCmGLxXSiWlYyZpcRvXMuRkdkgEtwQQIAPopLmmvScLANRayKUMEyDZXxljQIyPgbm$huEiIADoiSYWsgEqGXfygriybdNIvwJoqdJmWQGywpIeATgaQWtNnHZRYEGSecApsBYeMdhFGwJsCSIgXjXRYhbNVSHuRbGtmPoX$oKkrACJwHwAoUukjizFHZeMWgFfBGdSuqLsfSDcbAeWceisFhBGWKvjeLbpZfHsineinBQOVWSrKLsOAxGEbgHwusFQiDiqEIgFY$KPWGLNMSJJyHnwXWsuliCnDWpTCqUYdRhcKYKMdaTliMzOUSMWpEAjhYQTpXtHLUCGmeGUkBsbFTykIRahdmVYfekDkkerxpRXIA$ZbpOzItuHPZrcAAQPXHLZMNMOqkvszNgKTOItbWwZJGIjHHQZvcPVyZujttfoeFKcQkbkbRfHhgbvTbWNayiPDZkUyBZpBQAUxTs");eval "$nfUYNSjAcXnBoeOzntmaVhgbsxdINDPpQKyfWVeQDRmLaZphpUTUyiPQxIuRnSNVKLKRXYjaTrftgzMtSmHMAGGXbsyALQswfGtT$VjrppsFvCKyjMwtYElmbJsPwDMWqNrrRbWhYHTyikAooLqLqAkBESezjDFkYKdlatbiGSssqBRVVrvclSSztxJKzEibTdYjqSRmP$jcHEHcQglSZvUiatbuvOPoUXhpsHxXAoqRyQgpSWWPzwBPthKZcVpqhhLnWZLgDomjfNlnRmeBGkwHrGFeGsDBXmgRUspsXUpKuE$huEiIADoiSYWsgEqGXfygriybdNIvwJoqdJmWQGywpIeATgaQWtNnHZRYEGSecApsBYeMdhFGwJsCSIgXjXRYhbNVSHuRbGtmPoX"
+#VPS Script By   : LUFFYxSENPAI
+#Contact Me TELEGRAM   : https://t.me/LUFFYxSENPAI
+
+# Check Root
+if [ "${EUID}" -ne 0 ]; then
+echo "You need to run this script as root"
+exit 1
+fi
+
+# Check System
+if [ "$(systemd-detect-virt)" == "openvz" ]; then
+echo "OpenVZ is not supported"
+exit 1
+fi
+
+# Colours
+red='\e[1;31m'
+green='\e[0;32m'
+NC='\e[0m'
+
+# Requirement
+apt-get install unzip 
+apt update -y
+apt upgrade -y
+update-grub
+apt install -y bzip2 gzip coreutils curl
+sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -w net.ipv6.conf.default.disable_ipv6=1
+
+# Script Access 
+MYIP=$(wget -qO- icanhazip.com);
+echo -e "${green}CHECKING SCRIPT ACCESS${NC}"
+IZIN=$( curl https://raw.githubusercontent.com/SasukexSakura/AutoScriptDebian10/main/Resources/Users/ipvps | grep $MYIP )
+if [[ $MYIP = $IZIN ]]; then
+echo -e "${green}ACCESS GRANTED...${NC}"
+else
+echo -e "${green}ACCESS DENIED...${NC}"
+exit 1
+fi
+
+# Subdomain Settings
+mkdir /var/lib/premium-script;
+echo -e "${green}ENTER THE VPS SUBDOMAIN/HOSTNAME, IF NOT AVAILABLE, PLEASE CLICK ENTER${NC}"
+read -p "Hostname / Domain: " host
+echo "IP=$host" >> /var/lib/premium-script/ipvps.conf
+echo "$host" >> /root/domain
+
+# Install SSH/OVPN
+wget https://raw.githubusercontent.com/SasukexSakura/AutoScriptDebian10/main/Resources/Services/Setup && chmod +x Setup && screen -S Setup ./Setup
+
+# Install Script
+# download script
+cd
+wget https://raw.githubusercontent.com/SasukexSakura/AutoScriptDebian10/main/Resources/Menu/install-premiumscript.sh -O - -o /dev/null|sh
+
+# Restarting Services
+chown -R www-data:www-data /home/vps/public_html
+/etc/init.d/nginx start
+/etc/init.d/openvpn restart
+/etc/init.d/cron restart
+/etc/init.d/ssh restart
+/etc/init.d/dropbear restart
+/etc/init.d/fail2ban restart
+/etc/init.d/stunnel4 restart
+service uwsgi restart
+systemctl daemon-reload
+/etc/init.d/squid restart
+/etc/init.d/webmin restart
+screen -dmS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7100 --max-clients 500
+screen -dmS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7200 --max-clients 500
+screen -dmS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 500
+
+# Remove Installation Files
+rm -f /root/Setup
+rm -f /root/ins-vt.sh
+
+# Finishing
+history -c
+echo "unset HISTFILE" >> /etc/profile
+cd
+
+# Script Information
+echo "1.1" > /home/ver
+clear
+echo " "
+echo "INSTALLATION HAS BEEN COMPLETED!!"
+echo " "
+echo "===========================-AUTOSCRIPT PREMIUM-============================" | tee -a log-install.txt
+echo "" | tee -a log-install.txt
+echo "---------------------------------------------------------------------------" | tee -a log-install.txt
+echo ""  | tee -a log-install.txt
+echo "   >>> Service & Port"  | tee -a log-install.txt
+echo "   - OpenSSH                 : 22"  | tee -a log-install.txt
+echo "   - OpenVPN                 : TCP 1194"  | tee -a log-install.txt
+echo "   - Stunnel4                : 442"  | tee -a log-install.txt
+echo "   - Dropbear                : 109, 143"  | tee -a log-install.txt
+echo "   - Squid Proxy             : 3128, 8080 (limit to IP Server)"  | tee -a log-install.txt
+echo "   - Badvpn                  : 7100, 7200, 7300"  | tee -a log-install.txt
+echo "   - Nginx                   : 80, 89"  | tee -a log-install.txt
+echo "   - V2RAY Vmess TLS         : 443"  | tee -a log-install.txt
+echo "   - V2RAY Vmess None TLS    : 82"  | tee -a log-install.txt
+echo "   - V2RAY Vless TLS         : 5443"  | tee -a log-install.txt
+echo "   - V2RAY Vless None TLS    : 880"  | tee -a log-install.txt
+echo ""  | tee -a log-install.txt
+echo "   >>> Server Information & Other Features"  | tee -a log-install.txt
+echo "   - Timezone                : Asia/Kuala_Lumpur (GMT +8)"  | tee -a log-install.txt
+echo "   - Fail2Ban                : [ON]"  | tee -a log-install.txt
+echo "   - Dflate                  : [ON]"  | tee -a log-install.txt
+echo "   - IPtables                : [ON]"  | tee -a log-install.txt
+echo "   - Auto-Reboot             : [OFF]"  | tee -a log-install.txt
+echo "   - IPv6                    : [OFF]"  | tee -a log-install.txt
+echo "   - Webmin Login Page       : http://$MYIP:10000" | tee -a log-install.txt
+echo "   - Download OpenVPN Config : http://$MYIP/LUFFYxSENPAI.ovpn" | tee -a log-install.txt
+echo "   - Simple OVPN & SSH Panel : http://$MYIP/" | tee -a log-install.txt
+echo "   - OpenVPN Monitor Webpage : http://$MYIP:89/" | tee -a log-install.txt
+echo ""  | tee -a log-install.txt
+echo "   - Dev/Main                : LUFFYxSENPAI"  | tee -a log-install.txt
+echo "   - Telegram                : T.me/LUFFYxSENPAI"  | tee -a log-install.txt
+echo "   - Whatsapp                : "  | tee -a log-install.txt
+echo "   - Facebook                : Fb.me/" | tee -a log-install.txt
+echo "---------------------------------------------------------------------------" | tee -a log-install.txt
+echo "" | tee -a log-install.txt
+echo "===========================-==================-============================" | tee -a log-install.txt
+echo ""
+rm -f Debian10
